name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase (Staging)
        if: github.ref == 'refs/heads/staging'
        run: npx firebase deploy --only hosting:staging --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"

      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/main'
        run: npx firebase deploy --only hosting:production --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
