name: Jest
on: [push]

jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
